import { useEffect, useState } from 'react';
import { ArrowLeft, Check, ClipboardCheck, RefreshCw, Save, ShieldAlert } from 'lucide-react';
import { useNavigate, useParams } from 'react-router-dom';
import MainLayout from '../layouts/MainLayout';
import { apiFetch } from '../api';
import '../styles/pages.css';

const badgeClass = (status) => ({ ACTIVE: 'badge-success', PENDING_REVIEW: 'badge-warning', MODIFIED: 'badge-info', REJECTED: 'badge-danger' }[status] || 'badge-info');

export default function CarePlanDetails() {
  const { carePlanId } = useParams();
  const navigate = useNavigate();
  const [plan, setPlan] = useState(null);
  const [adherence, setAdherence] = useState({});
  const [outcomes, setOutcomes] = useState([]);
  const [comment, setComment] = useState('');
  const [intervention, setIntervention] = useState('');
  const [error, setError] = useState('');
  const [busy, setBusy] = useState(false);

  useEffect(() => {
    Promise.all([
      apiFetch(`/api/careplans/${carePlanId}`),
      apiFetch(`/api/careplans/${carePlanId}/adherence/statistics`),
      apiFetch(`/api/careplans/${carePlanId}/outcomes`),
    ]).then(([carePlan, stats, results]) => { setPlan(carePlan); setAdherence(stats); setOutcomes(results); setIntervention(carePlan.interventions?.[0]?.description || ''); }).catch((requestError) => setError(requestError.message));
  }, [carePlanId]);

  const action = async (path, options = {}) => { setBusy(true); setError(''); try { await apiFetch(path, { method: 'POST', ...options }); const [carePlan, stats, results] = await Promise.all([apiFetch(`/api/careplans/${carePlanId}`), apiFetch(`/api/careplans/${carePlanId}/adherence/statistics`), apiFetch(`/api/careplans/${carePlanId}/outcomes`)]); setPlan(carePlan); setAdherence(stats); setOutcomes(results); } catch (requestError) { setError(requestError.message); } finally { setBusy(false); } };
  const review = (verb) => action(`/api/careplans/${carePlanId}/${verb}`, { body: JSON.stringify({ comments: comment || `Provider ${verb} review` }) });
  const modify = () => action(`/api/careplans/${carePlanId}/modify`, { body: JSON.stringify({ comments: comment || 'Provider modified intervention', interventions: [{ ...plan.interventions?.[0], description: intervention, status: 'PROPOSED' }] }) });
  const record = (status) => action(`/api/careplans/${carePlanId}/adherence`, { body: JSON.stringify({ patientId: plan.patientId, taskId: plan.monitoringTasks?.[0]?.taskId, date: new Date().toISOString().slice(0, 10), status, notes: comment }) });
  const addOutcome = () => action(`/api/careplans/${carePlanId}/outcomes`, { body: JSON.stringify({ patientId: plan.patientId, metric: plan.expectedOutcomes?.[0]?.metric || 'BLOOD_PRESSURE_SYSTOLIC', baselineValue: plan.expectedOutcomes?.[0]?.baselineValue, currentValue: 128, targetValue: plan.expectedOutcomes?.[0]?.expectedValue || 130, unit: plan.expectedOutcomes?.[0]?.unit || 'mmHg' }) });

  if (!plan) return <MainLayout title="Care Plan Details"><p>{error || 'Loading care plan...'}</p></MainLayout>;
  return <MainLayout title="Care Plan Details"><div className="dashboard-container careplans-page">
    <button className="btn btn-ghost" onClick={() => navigate('/careplans')}><ArrowLeft size={15} /> Back to care plans</button>
    {error && <p className="error-message">{error}</p>}
    <div className="dashboard-header"><p className="eyebrow"><ClipboardCheck size={15} /> Care plan detail</p><h2>{plan.title}</h2><p className="dashboard-subtitle">Patient {plan.patientId} · Generated by {plan.generatedBy || 'MediSphere'} · Synthetic decision support requiring clinician review.</p></div>
    <div className="stats-grid"><div className="stat-card"><div className="stat-content"><div className="stat-label">Plan status</div><div className="stat-value"><span className={`badge ${badgeClass(plan.status)}`}>{plan.status}</span></div></div><ClipboardCheck className="stat-icon" /></div><div className="stat-card"><div className="stat-content"><div className="stat-label">Adherence</div><div className="stat-value">{Number(adherence.adherencePercentage || 0).toFixed(0)}%</div><p>{adherence.completedTasks || 0} completed · {adherence.missedTasks || 0} missed · {adherence.pendingTasks || 0} pending</p></div><Check className="stat-icon" /></div><div className="stat-card"><div className="stat-content"><div className="stat-label">Guideline validation</div><div className="stat-value">{plan.guidelineValidation?.compliant ? 'PASS' : 'REVIEW'}</div></div><ShieldAlert className="stat-icon" /></div></div>
    <div className="activity-grid"><div className="card"><h3 className="chart-title">Patient and risk summary</h3><p>{plan.description}</p><p>Risk category: {plan.riskInformation?.riskCategory || 'Not available'} · Probability: {plan.riskInformation?.riskPercentage == null ? 'Not available' : `${plan.riskInformation.riskPercentage}%`}</p><h4>AI reasoning / risk factors</h4>{plan.riskInformation?.explanation?.slice?.(0, 4).map((item) => <p key={item.feature}>{item.label || item.feature}: {item.summary || 'Persisted model contribution'}</p>)}<h4>Goals</h4>{plan.goals?.map((goal) => <p key={goal.targetMetric}>{goal.description} · {goal.targetMetric}: {goal.targetValue} {goal.targetUnit}</p>)}</div><div className="card"><h3 className="chart-title">Guideline validation and safety</h3><p>{plan.guidelineValidation?.compliant ? 'Compliant with configurable demo rules.' : 'Needs provider review before activation.'}</p><p>Rules checked: {plan.guidelineValidation?.rulesChecked || 0}</p>{plan.guidelineValidation?.warnings?.map((warning) => <p key={warning} className="dashboard-subtitle">Warning: {warning}</p>)}{plan.guidelineValidation?.errors?.map((validationError) => <p key={validationError} className="error-message">Safety issue: {validationError}</p>)}<h4>Monitoring tasks</h4>{plan.monitoringTasks?.map((task) => <p key={task.taskId}>{task.metric} · {task.frequency} · {task.targetRange}</p>)}</div></div>
    <div className="card"><h3 className="chart-title">Provider review and intervention management</h3><textarea value={comment} onChange={(event) => setComment(event.target.value)} placeholder="Provider comments" rows="3" /><input value={intervention} onChange={(event) => setIntervention(event.target.value)} placeholder="Intervention description" /><div className="action-buttons"><button className="action-btn" disabled={busy} onClick={() => action(`/api/careplans/${carePlanId}/validate`)}><RefreshCw size={14} /> Validate</button>{['PENDING_REVIEW', 'MODIFIED'].includes(plan.status) && <><button className="action-btn" disabled={busy} onClick={() => review('approve')}>Approve</button><button className="action-btn" disabled={busy} onClick={modify}><Save size={14} /> Modify</button><button className="action-btn" disabled={busy} onClick={() => review('reject')}>Reject</button></>}{plan.status === 'ACTIVE' && <><button className="action-btn" disabled={busy} onClick={() => record('COMPLETED')}>Complete task</button><button className="action-btn" disabled={busy} onClick={() => record('MISSED')}>Mark missed</button></>}<button className="action-btn" disabled={busy} onClick={addOutcome}>Record outcome</button></div><p className="ai-disclaimer">Provider: {plan.reviewedBy || 'Pending'} · Comments: {plan.reviewComments || 'None'}</p></div>
    <div className="table-wrapper"><div className="monitoring-table-header"><div><h3 className="section-title">Outcome measurement</h3><p className="section-subtitle">Baseline, current, target, change, and progress from persisted measurements.</p></div></div><div className="table-responsive"><table><thead><tr><th>Metric</th><th>Baseline</th><th>Current</th><th>Target</th><th>Change</th><th>Progress</th></tr></thead><tbody>{outcomes.map((outcome) => <tr key={outcome.outcomeId}><td>{outcome.metric}</td><td>{outcome.baselineValue ?? 'N/A'}</td><td>{outcome.currentValue}</td><td>{outcome.targetValue}</td><td>{outcome.change ?? 'N/A'}</td><td>{outcome.progressPercentage == null ? 'N/A' : `${Number(outcome.progressPercentage).toFixed(0)}%`}</td></tr>)}{!outcomes.length && <tr><td colSpan="6" className="empty-state">No measured outcomes yet.</td></tr>}</tbody></table></div></div>
    <div className="card"><h3 className="chart-title">Timeline / audit history</h3>{plan.timeline?.map((event) => <p key={event}>{event}</p>)}</div>
  </div></MainLayout>;
}